const priceStatusList = [
    {
        "id": "yrgsIRO8WX_YaurXfovuB",
        "component": "Group",
        "label": "组合",
        "icon": "zuhe",
        "groupStyle": {},
        "isPriceStatus": true,
        "isLock": false,
        "collapseName": "base",
        "style": {
            "rotate": 0,
            "opacity": 1,
            "left": 0,
            "top": 0,
            "width": 317,
            "height": 79,
            "name": "group_0",
            "objAlign": 1
        },
        "propValue": [
            {
                "groupStyle": {
                    "transform": "rotate(0deg)",
                    "opacity": 1,
                    "parent": "bg_scr",
                    "name": "gpunG_1",
                    "base": "bg_scr",
                    "str": "促销价：",
                    "width": "40.694006309148264%",
                    "height": "53.16455696202531%",
                    "font": "./res/font/bls.ttf",
                    "fontSize": "32px",
                    "fontWeight": 400,
                    "letterSpacing": "0px",
                    "textAlign": "left",
                    "longMode": 0,
                    "baseLine": 6,
                    "color": "rgba(255, 255, 255, 1)",
                    "backgroundColor": "rgba(0, 0, 0, 1)",
                    "display": "block",
                    "objAlign": 1,
                    "xOffset": 197,
                    "yOffset": 265,
                    "top": "0%",
                    "left": "0%"
                },
                "isLock": false,
                "isPriceStatus": true,
                "collapseName": "base",
                "component": "VText",
                "label": "商品附加信息",
                "type": "label",
                "propValue": "",
                "icon": "wenben",
                "tag": "normal",
                "style": {
                    "rotate": 0,
                    "opacity": 1,
                    "parent": "bg_scr",
                    "name": "gpunG_1",
                    "base": "bg_scr",
                    "str": "促销价：",
                    "width": 129,
                    "height": 42,
                    "font": "./res/font/bls.ttf",
                    "fontSize": 32,
                    "fontWeight": 400,
                    "lineHeight": "",
                    "letterSpacing": 0,
                    "textAlign": "left",
                    "longMode": 0,
                    "baseLine": 6,
                    "color": "rgba(255, 255, 255, 1)",
                    "backgroundColor": "rgba(0, 0, 0, 1)",
                    "display": false,
                    "objAlign": 1,
                    "xOffset": 197,
                    "yOffset": 265,
                    "top": 265,
                    "left": 197
                },
                "id": "ILhM9H6qz8u-w7-SL92JK"
            },
            {
                "groupStyle": {
                    "transform": "rotate(0deg)",
                    "opacity": 1,
                    "parent": "bg_scr",
                    "name": "pbNG_1",
                    "base": "bg_scr",
                    "numStr": "88.00",
                    "width": "56.782334384858046%",
                    "height": "100%",
                    "font": "./res/font/bls_pri.ttf",
                    "fontSize": "60px",
                    "fontWeight": 600,
                    "letterSpacing": "0px",
                    "textAlign": "center",
                    "longMode": 0,
                    "baseLine": 7,
                    "color": "rgba(255, 255, 255, 1)",
                    "backgroundColor": "rgba(0, 0, 0, 1)",
                    "display": "block",
                    "objAlign": 1,
                    "xOffset": 334,
                    "yOffset": 265,
                    "top": "0%",
                    "left": "43.217665615141954%"
                },
                "isLock": false,
                "isPriceStatus": true,
                "collapseName": "base",
                "component": "VText",
                "label": "价格    ",
                "type": "label",
                "propValue": "",
                "icon": "wenben",
                "tag": "price",
                "style": {
                    "rotate": 0,
                    "opacity": 1,
                    "parent": "bg_scr",
                    "name": "pbNG_1",
                    "base": "bg_scr",
                    "numStr": "88.00",
                    "width": 180,
                    "height": 79,
                    "font": "./res/font/bls_pri.ttf",
                    "fontSize": 60,
                    "fontWeight": 600,
                    "lineHeight": "",
                    "letterSpacing": 0,
                    "textAlign": "center",
                    "longMode": 0,
                    "baseLine": 7,
                    "color": "rgba(255, 255, 255, 1)",
                    "backgroundColor": "rgba(0, 0, 0, 1)",
                    "display": false,
                    "objAlign": 1,
                    "xOffset": 334,
                    "yOffset": 265,
                    "top": 265,
                    "left": 334
                },
                "id": "PU5rNjuuCioi3HtBcaIt-"
            }
        ],
        "type": "group"
    },
    {
        "id": "kguVkJjTwW3-axkbdvo0E",
        "component": "Group",
        "label": "组合",
        "icon": "zuhe",
        "groupStyle": {},
        "isLock": false,
        "isPriceStatus": true,
        "collapseName": "base",
        "style": {
            "rotate": 0,
            "opacity": 1,
            "left": 226,
            "top": 307,
            "width": 317,
            "height": 122,
            "name": "group_0",
            "objAlign": 1
        },
        "propValue": [
            {
                "groupStyle": {
                    "transform": "rotate(0deg)",
                    "opacity": 1,
                    "parent": "bg_scr",
                    "name": "gpbnG_2",
                    "base": "bg_scr",
                    "str": "零售价：",
                    "width": "40.694006309148264%",
                    "height": "34.42622950819672%",
                    "font": "./res/font/bls.ttf",
                    "fontSize": "32px",
                    "fontWeight": 400,
                    "letterSpacing": "0px",
                    "textAlign": "left",
                    "longMode": 0,
                    "baseLine": 6,
                    "color": "rgba(255, 255, 255, 1)",
                    "backgroundColor": "rgba(0, 0, 0, 1)",
                    "display": "block",
                    "objAlign": 1,
                    "xOffset": 226,
                    "yOffset": 307,
                    "top": "0%",
                    "left": "0%"
                },
                "isLock": false,
                "isPriceStatus": true,
                "collapseName": "base",
                "component": "VText",
                "label": "商品附加信息",
                "type": "label",
                "propValue": "",
                "icon": "wenben",
                "tag": "normal",
                "style": {
                    "rotate": 0,
                    "opacity": 1,
                    "parent": "bg_scr",
                    "name": "gpbnG_2",
                    "base": "bg_scr",
                    "str": "零售价：",
                    "width": 129,
                    "height": 42,
                    "font": "./res/font/bls.ttf",
                    "fontSize": 32,
                    "fontWeight": 400,
                    "lineHeight": "",
                    "letterSpacing": 0,
                    "textAlign": "left",
                    "longMode": 0,
                    "baseLine": 6,
                    "color": "rgba(255, 255, 255, 1)",
                    "backgroundColor": "rgba(0, 0, 0, 1)",
                    "display": false,
                    "objAlign": 1,
                    "xOffset": 226,
                    "yOffset": 307,
                    "top": 307,
                    "left": 226
                },
                "id": "ILhM9H6qz8u-w7-SL92JK"
            },
            {
                "groupStyle": {
                    "transform": "rotate(0deg)",
                    "opacity": 1,
                    "parent": "bg_scr",
                    "name": "pbNG_2",
                    "base": "bg_scr",
                    "numStr": "88.00",
                    "width": "56.782334384858046%",
                    "height": "64.75409836065575%",
                    "font": "./res/font/bls_pri.ttf",
                    "fontSize": "60px",
                    "fontWeight": 600,
                    "letterSpacing": "0px",
                    "textAlign": "center",
                    "longMode": 0,
                    "baseLine": 7,
                    "color": "rgba(255, 255, 255, 1)",
                    "backgroundColor": "rgba(0, 0, 0, 1)",
                    "display": "block",
                    "objAlign": 1,
                    "xOffset": 363,
                    "yOffset": 307,
                    "top": "0%",
                    "left": "43.217665615141954%"
                },
                "isLock": false,
                "isPriceStatus": true,
                "collapseName": "base",
                "component": "VText",
                "label": "价格    ",
                "type": "label",
                "propValue": "",
                "icon": "wenben",
                "tag": "price",
                "style": {
                    "rotate": 0,
                    "opacity": 1,
                    "parent": "bg_scr",
                    "name": "pbNG_2",
                    "base": "bg_scr",
                    "numStr": "88.00",
                    "width": 180,
                    "height": 79,
                    "font": "./res/font/bls_pri.ttf",
                    "fontSize": 60,
                    "fontWeight": 600,
                    "lineHeight": "",
                    "letterSpacing": 0,
                    "textAlign": "center",
                    "longMode": 0,
                    "baseLine": 7,
                    "color": "rgba(255, 255, 255, 1)",
                    "backgroundColor": "rgba(0, 0, 0, 1)",
                    "display": false,
                    "objAlign": 1,
                    "xOffset": 363,
                    "yOffset": 307,
                    "top": 307,
                    "left": 363
                },
                "id": "PU5rNjuuCioi3HtBcaIt-"
            },
            {
                "groupStyle": {
                    "transform": "rotate(0deg)",
                    "opacity": 1,
                    "parent": "bg_scr",
                    "name": "gpunG_2",
                    "base": "bg_scr",
                    "str": "原价：",
                    "width": "21.13564668769716%",
                    "height": "23.770491803278688%",
                    "font": "./res/font/bls.ttf",
                    "fontSize": "22px",
                    "fontWeight": 400,
                    "letterSpacing": "0px",
                    "textAlign": "left",
                    "longMode": 0,
                    "baseLine": 6,
                    "color": "rgba(0, 0, 0, 1)",
                    "backgroundColor": "rgba(255, 255, 255, 0)",
                    "display": "block",
                    "objAlign": 1,
                    "xOffset": 391,
                    "yOffset": 400,
                    "top": "76.22950819672131%",
                    "left": "52.05047318611987%"
                },
                "isLock": false,
                "isPriceStatus": true,
                "collapseName": "base",
                "component": "VText",
                "label": "商品名称",
                "type": "label",
                "propValue": "",
                "icon": "wenben",
                "tag": "normal",
                "style": {
                    "rotate": 0,
                    "opacity": 1,
                    "parent": "bg_scr",
                    "name": "gpunG_2",
                    "base": "bg_scr",
                    "str": "原价：",
                    "width": 67,
                    "height": 29,
                    "font": "./res/font/bls.ttf",
                    "fontSize": 22,
                    "fontWeight": 400,
                    "lineHeight": "",
                    "letterSpacing": 0,
                    "textAlign": "left",
                    "longMode": 0,
                    "baseLine": 6,
                    "color": "rgba(0, 0, 0, 1)",
                    "backgroundColor": "rgba(255, 255, 255, 0)",
                    "display": false,
                    "objAlign": 1,
                    "xOffset": 391,
                    "yOffset": 400,
                    "top": 400,
                    "left": 391
                },
                "id": "zcqJeOgGbu8AEnpBMeLCU"
            },
            {
                "groupStyle": {
                    "transform": "rotate(0deg)",
                    "opacity": 1,
                    "parent": "bg_scr",
                    "name": "puNG_2",
                    "base": "bg_scr",
                    "str": "99.00",
                    "width": "18.29652996845426%",
                    "height": "23.770491803278688%",
                    "font": "./res/font/bls.ttf",
                    "fontSize": "22px",
                    "fontWeight": 400,
                    "letterSpacing": "0px",
                    "textAlign": "left",
                    "longMode": 0,
                    "baseLine": 6,
                    "color": "rgba(0, 0, 0, 1)",
                    "backgroundColor": "rgba(255, 255, 255, 0)",
                    "display": "block",
                    "objAlign": 1,
                    "xOffset": 458,
                    "yOffset": 400,
                    "top": "76.22950819672131%",
                    "left": "73.18611987381703%"
                },
                "isLock": false,
                "isPriceStatus": true,
                "collapseName": "base",
                "component": "VText",
                "label": "商品名称",
                "type": "label",
                "propValue": "",
                "icon": "wenben",
                "tag": "normal",
                "style": {
                    "rotate": 0,
                    "opacity": 1,
                    "parent": "bg_scr",
                    "name": "puNG_2",
                    "base": "bg_scr",
                    "str": "99.00",
                    "width": 58,
                    "height": 29,
                    "font": "./res/font/bls.ttf",
                    "fontSize": 22,
                    "fontWeight": 400,
                    "lineHeight": "",
                    "letterSpacing": 0,
                    "textAlign": "left",
                    "longMode": 0,
                    "baseLine": 6,
                    "color": "rgba(0, 0, 0, 1)",
                    "backgroundColor": "rgba(255, 255, 255, 0)",
                    "display": false,
                    "objAlign": 1,
                    "xOffset": 458,
                    "yOffset": 400,
                    "top": 400,
                    "left": 458
                },
                "id": "v1nLPR3_50bltNoRIUKsA"
            },
            {
                "groupStyle": {
                    "transform": "rotate(0deg)",
                    "opacity": 1,
                    "name": "gpulG",
                    "parent": "bg_scr",
                    "width": "54.25867507886435%",
                    "height": "0.819672131147541%",
                    "backgroundColor": "rgba(159, 153, 153, 1)",
                    "display": "block",
                    "objAlign": 1,
                    "xOffset": 367,
                    "yOffset": 414,
                    "top": "87.70491803278688%",
                    "left": "44.479495268138805%",
                    "base": "bg_scr"
                },
                "isLock": false,
                "isPriceStatus": true,
                "collapseName": "base",
                "component": "LineShape",
                "label": "线条",
                "propValue": "",
                "type": "line",
                "icon": "zhixian",
                "tag": "normal",
                "style": {
                    "rotate": 0,
                    "opacity": 1,
                    "name": "gpulG",
                    "parent": "bg_scr",
                    "width": 172,
                    "height": 1,
                    "backgroundColor": "rgba(159, 153, 153, 1)",
                    "display": false,
                    "objAlign": 1,
                    "xOffset": 367,
                    "yOffset": 414,
                    "top": 414,
                    "left": 367,
                    "base": "bg_scr"
                },
                "id": "dJJr4zvqunLfLIndxZ1xn"
            }
        ],
        "type": "group"
    },
    {
        "id": "kguVkJjTwW3-axkbdvo0E",
        "component": "Group",
        "label": "组合",
        "icon": "zuhe",
        "groupStyle": {},
        "isLock": false,
        "isPriceStatus": true,
        "collapseName": "base",
        "style": {
            "rotate": 0,
            "opacity": 1,
            "left": 226,
            "top": 307,
            "width": 317,
            "height": 122,
            "name": "group_0",
            "objAlign": 1
        },
        "propValue": [
            {
                "groupStyle": {
                    "transform": "rotate(0deg)",
                    "opacity": 1,
                    "parent": "bg_scr",
                    "name": "gpvnG_3",
                    "base": "bg_scr",
                    "str": "会员价：",
                    "width": "40.694006309148264%",
                    "height": "34.42622950819672%",
                    "font": "./res/font/bls.ttf",
                    "fontSize": "32px",
                    "fontWeight": 400,
                    "letterSpacing": "0px",
                    "textAlign": "left",
                    "longMode": 0,
                    "baseLine": 6,
                    "color": "rgba(255, 255, 255, 1)",
                    "backgroundColor": "rgba(0, 0, 0, 1)",
                    "display": "block",
                    "objAlign": 1,
                    "xOffset": 226,
                    "yOffset": 307,
                    "top": "0%",
                    "left": "0%"
                },
                "isLock": false,
                "isPriceStatus": true,
                "collapseName": "base",
                "component": "VText",
                "label": "商品附加信息",
                "type": "label",
                "propValue": "",
                "icon": "wenben",
                "tag": "normal",
                "style": {
                    "rotate": 0,
                    "opacity": 1,
                    "parent": "bg_scr",
                    "name": "gpvnG_3",
                    "base": "bg_scr",
                    "str": "会员价：",
                    "width": 129,
                    "height": 42,
                    "font": "./res/font/bls.ttf",
                    "fontSize": 32,
                    "fontWeight": 400,
                    "lineHeight": "",
                    "letterSpacing": 0,
                    "textAlign": "left",
                    "longMode": 0,
                    "baseLine": 6,
                    "color": "rgba(255, 255, 255, 1)",
                    "backgroundColor": "rgba(0, 0, 0, 1)",
                    "display": false,
                    "objAlign": 1,
                    "xOffset": 226,
                    "yOffset": 307,
                    "top": 307,
                    "left": 226
                },
                "id": "ILhM9H6qz8u-w7-SL92JK"
            },
            {
                "groupStyle": {
                    "transform": "rotate(0deg)",
                    "opacity": 1,
                    "parent": "bg_scr",
                    "name": "pvNG_3",
                    "base": "bg_scr",
                    "numStr": "88.00",
                    "width": "56.782334384858046%",
                    "height": "64.75409836065575%",
                    "font": "./res/font/bls_pri.ttf",
                    "fontSize": "60px",
                    "fontWeight": 600,
                    "letterSpacing": "0px",
                    "textAlign": "center",
                    "longMode": 0,
                    "baseLine": 7,
                    "color": "rgba(255, 255, 255, 1)",
                    "backgroundColor": "rgba(0, 0, 0, 1)",
                    "display": "block",
                    "objAlign": 1,
                    "xOffset": 363,
                    "yOffset": 307,
                    "top": "0%",
                    "left": "43.217665615141954%"
                },
                "isLock": false,
                "isPriceStatus": true,
                "collapseName": "base",
                "component": "VText",
                "label": "价格    ",
                "type": "label",
                "propValue": "",
                "icon": "wenben",
                "tag": "price",
                "style": {
                    "rotate": 0,
                    "opacity": 1,
                    "parent": "bg_scr",
                    "name": "pvNG_3",
                    "base": "bg_scr",
                    "numStr": "88.00",
                    "width": 180,
                    "height": 79,
                    "font": "./res/font/bls_pri.ttf",
                    "fontSize": 60,
                    "fontWeight": 600,
                    "lineHeight": "",
                    "letterSpacing": 0,
                    "textAlign": "center",
                    "longMode": 0,
                    "baseLine": 7,
                    "color": "rgba(255, 255, 255, 1)",
                    "backgroundColor": "rgba(0, 0, 0, 1)",
                    "display": false,
                    "objAlign": 1,
                    "xOffset": 363,
                    "yOffset": 307,
                    "top": 307,
                    "left": 363
                },
                "id": "PU5rNjuuCioi3HtBcaIt-"
            },
            {
                "groupStyle": {
                    "transform": "rotate(0deg)",
                    "opacity": 1,
                    "parent": "bg_scr",
                    "name": "gpunG_3",
                    "base": "bg_scr",
                    "str": "原价：",
                    "width": "21.13564668769716%",
                    "height": "23.770491803278688%",
                    "font": "./res/font/bls.ttf",
                    "fontSize": "22px",
                    "fontWeight": 400,
                    "letterSpacing": "0px",
                    "textAlign": "left",
                    "longMode": 0,
                    "baseLine": 6,
                    "color": "rgba(0, 0, 0, 1)",
                    "backgroundColor": "rgba(255, 255, 255, 0)",
                    "display": "block",
                    "objAlign": 1,
                    "xOffset": 391,
                    "yOffset": 400,
                    "top": "76.22950819672131%",
                    "left": "52.05047318611987%"
                },
                "isLock": false,
                "isPriceStatus": true,
                "collapseName": "base",
                "component": "VText",
                "label": "商品名称",
                "type": "label",
                "propValue": "",
                "icon": "wenben",
                "tag": "normal",
                "style": {
                    "rotate": 0,
                    "opacity": 1,
                    "parent": "bg_scr",
                    "name": "gpunG_3",
                    "base": "bg_scr",
                    "str": "原价：",
                    "width": 67,
                    "height": 29,
                    "font": "./res/font/bls.ttf",
                    "fontSize": 22,
                    "fontWeight": 400,
                    "lineHeight": "",
                    "letterSpacing": 0,
                    "textAlign": "left",
                    "longMode": 0,
                    "baseLine": 6,
                    "color": "rgba(0, 0, 0, 1)",
                    "backgroundColor": "rgba(255, 255, 255, 0)",
                    "display": false,
                    "objAlign": 1,
                    "xOffset": 391,
                    "yOffset": 400,
                    "top": 400,
                    "left": 391
                },
                "id": "zcqJeOgGbu8AEnpBMeLCU"
            },
            {
                "groupStyle": {
                    "transform": "rotate(0deg)",
                    "opacity": 1,
                    "parent": "bg_scr",
                    "name": "puNG_3",
                    "base": "bg_scr",
                    "str": "99.00",
                    "width": "18.29652996845426%",
                    "height": "23.770491803278688%",
                    "font": "./res/font/bls.ttf",
                    "fontSize": "22px",
                    "fontWeight": 400,
                    "letterSpacing": "0px",
                    "textAlign": "left",
                    "longMode": 0,
                    "baseLine": 6,
                    "color": "rgba(0, 0, 0, 1)",
                    "backgroundColor": "rgba(255, 255, 255, 0)",
                    "display": "block",
                    "objAlign": 1,
                    "xOffset": 458,
                    "yOffset": 400,
                    "top": "76.22950819672131%",
                    "left": "73.18611987381703%"
                },
                "isLock": false,
                "isPriceStatus": true,
                "collapseName": "base",
                "component": "VText",
                "label": "商品名称",
                "type": "label",
                "propValue": "",
                "icon": "wenben",
                "tag": "normal",
                "style": {
                    "rotate": 0,
                    "opacity": 1,
                    "parent": "bg_scr",
                    "name": "puNG_3",
                    "base": "bg_scr",
                    "str": "99.00",
                    "width": 58,
                    "height": 29,
                    "font": "./res/font/bls.ttf",
                    "fontSize": 22,
                    "fontWeight": 400,
                    "lineHeight": "",
                    "letterSpacing": 0,
                    "textAlign": "left",
                    "longMode": 0,
                    "baseLine": 6,
                    "color": "rgba(0, 0, 0, 1)",
                    "backgroundColor": "rgba(255, 255, 255, 0)",
                    "display": false,
                    "objAlign": 1,
                    "xOffset": 458,
                    "yOffset": 400,
                    "top": 400,
                    "left": 458
                },
                "id": "v1nLPR3_50bltNoRIUKsA"
            },
            {
                "groupStyle": {
                    "transform": "rotate(0deg)",
                    "opacity": 1,
                    "name": "gpulG",
                    "parent": "bg_scr",
                    "width": "54.25867507886435%",
                    "height": "0.819672131147541%",
                    "backgroundColor": "rgba(159, 153, 153, 1)",
                    "display": "block",
                    "objAlign": 1,
                    "xOffset": 367,
                    "yOffset": 414,
                    "top": "87.70491803278688%",
                    "left": "44.479495268138805%",
                    "base": "bg_scr"
                },
                "isLock": false,
                "isPriceStatus": true,
                "collapseName": "base",
                "component": "LineShape",
                "label": "线条",
                "propValue": "",
                "type": "line",
                "icon": "zhixian",
                "tag": "normal",
                "style": {
                    "rotate": 0,
                    "opacity": 1,
                    "name": "gpulG",
                    "parent": "bg_scr",
                    "width": 172,
                    "height": 1,
                    "backgroundColor": "rgba(159, 153, 153, 1)",
                    "display": false,
                    "objAlign": 1,
                    "xOffset": 367,
                    "yOffset": 414,
                    "top": 414,
                    "left": 367,
                    "base": "bg_scr"
                },
                "id": "dJJr4zvqunLfLIndxZ1xn"
            }
        ],
        "type": "group"
    },
    {
        "id": "kguVkJjTwW3-axkbdvo0E",
        "component": "Group",
        "label": "组合",
        "icon": "zuhe",
        "groupStyle": {},
        "isLock": false,
        "isPriceStatus": true,
        "collapseName": "base",
        "style": {
            "rotate": 0,
            "opacity": 1,
            "left": 226,
            "top": 307,
            "width": 317,
            "height": 122,
            "name": "group_0",
            "objAlign": 1
        },
        "propValue": [
            {
                "groupStyle": {
                    "transform": "rotate(0deg)",
                    "opacity": 1,
                    "parent": "bg_scr",
                    "name": "gpynG_4",
                    "base": "bg_scr",
                    "str": "胖柚价：",
                    "width": "40.694006309148264%",
                    "height": "34.42622950819672%",
                    "font": "./res/font/bls.ttf",
                    "fontSize": "32px",
                    "fontWeight": 400,
                    "letterSpacing": "0px",
                    "textAlign": "left",
                    "longMode": 0,
                    "baseLine": 6,
                    "color": "rgba(255, 255, 255, 1)",
                    "backgroundColor": "rgba(0, 0, 0, 1)",
                    "display": "block",
                    "objAlign": 1,
                    "xOffset": 226,
                    "yOffset": 307,
                    "top": "0%",
                    "left": "0%"
                },
                "isLock": false,
                "isPriceStatus": true,
                "collapseName": "base",
                "component": "VText",
                "label": "商品附加信息",
                "type": "label",
                "propValue": "",
                "icon": "wenben",
                "tag": "normal",
                "style": {
                    "rotate": 0,
                    "opacity": 1,
                    "parent": "bg_scr",
                    "name": "gpynG_4",
                    "base": "bg_scr",
                    "str": "胖柚价：",
                    "width": 129,
                    "height": 42,
                    "font": "./res/font/bls.ttf",
                    "fontSize": 32,
                    "fontWeight": 400,
                    "lineHeight": "",
                    "letterSpacing": 0,
                    "textAlign": "left",
                    "longMode": 0,
                    "baseLine": 6,
                    "color": "rgba(255, 255, 255, 1)",
                    "backgroundColor": "rgba(0, 0, 0, 1)",
                    "display": false,
                    "objAlign": 1,
                    "xOffset": 226,
                    "yOffset": 307,
                    "top": 307,
                    "left": 226
                },
                "id": "ILhM9H6qz8u-w7-SL92JK"
            },
            {
                "groupStyle": {
                    "transform": "rotate(0deg)",
                    "opacity": 1,
                    "parent": "bg_scr",
                    "name": "pyNG_4",
                    "base": "bg_scr",
                    "numStr": "88.00",
                    "width": "56.782334384858046%",
                    "height": "64.75409836065575%",
                    "font": "./res/font/bls_pri.ttf",
                    "fontSize": "60px",
                    "fontWeight": 600,
                    "letterSpacing": "0px",
                    "textAlign": "center",
                    "longMode": 0,
                    "baseLine": 7,
                    "color": "rgba(255, 255, 255, 1)",
                    "backgroundColor": "rgba(0, 0, 0, 1)",
                    "display": "block",
                    "objAlign": 1,
                    "xOffset": 363,
                    "yOffset": 307,
                    "top": "0%",
                    "left": "43.217665615141954%"
                },
                "isLock": false,
                "isPriceStatus": true,
                "collapseName": "base",
                "component": "VText",
                "label": "价格    ",
                "type": "label",
                "propValue": "",
                "icon": "wenben",
                "tag": "price",
                "style": {
                    "rotate": 0,
                    "opacity": 1,
                    "parent": "bg_scr",
                    "name": "pyNG_4",
                    "base": "bg_scr",
                    "numStr": "88.00",
                    "width": 180,
                    "height": 79,
                    "font": "./res/font/bls_pri.ttf",
                    "fontSize": 60,
                    "fontWeight": 600,
                    "lineHeight": "",
                    "letterSpacing": 0,
                    "textAlign": "center",
                    "longMode": 0,
                    "baseLine": 7,
                    "color": "rgba(255, 255, 255, 1)",
                    "backgroundColor": "rgba(0, 0, 0, 1)",
                    "display": false,
                    "objAlign": 1,
                    "xOffset": 363,
                    "yOffset": 307,
                    "top": 307,
                    "left": 363
                },
                "id": "PU5rNjuuCioi3HtBcaIt-"
            },
            {
                "groupStyle": {
                    "transform": "rotate(0deg)",
                    "opacity": 1,
                    "parent": "bg_scr",
                    "name": "gpunG_4",
                    "base": "bg_scr",
                    "str": "原价：",
                    "width": "21.13564668769716%",
                    "height": "23.770491803278688%",
                    "font": "./res/font/bls.ttf",
                    "fontSize": "22px",
                    "fontWeight": 400,
                    "letterSpacing": "0px",
                    "textAlign": "left",
                    "longMode": 0,
                    "baseLine": 6,
                    "color": "rgba(0, 0, 0, 1)",
                    "backgroundColor": "rgba(255, 255, 255, 0)",
                    "display": "block",
                    "objAlign": 1,
                    "xOffset": 391,
                    "yOffset": 400,
                    "top": "76.22950819672131%",
                    "left": "52.05047318611987%"
                },
                "isLock": false,
                "isPriceStatus": true,
                "collapseName": "base",
                "component": "VText",
                "label": "商品名称",
                "type": "label",
                "propValue": "",
                "icon": "wenben",
                "tag": "normal",
                "style": {
                    "rotate": 0,
                    "opacity": 1,
                    "parent": "bg_scr",
                    "name": "gpunG_4",
                    "base": "bg_scr",
                    "str": "原价：",
                    "width": 67,
                    "height": 29,
                    "font": "./res/font/bls.ttf",
                    "fontSize": 22,
                    "fontWeight": 400,
                    "lineHeight": "",
                    "letterSpacing": 0,
                    "textAlign": "left",
                    "longMode": 0,
                    "baseLine": 6,
                    "color": "rgba(0, 0, 0, 1)",
                    "backgroundColor": "rgba(255, 255, 255, 0)",
                    "display": false,
                    "objAlign": 1,
                    "xOffset": 391,
                    "yOffset": 400,
                    "top": 400,
                    "left": 391
                },
                "id": "zcqJeOgGbu8AEnpBMeLCU"
            },
            {
                "groupStyle": {
                    "transform": "rotate(0deg)",
                    "opacity": 1,
                    "parent": "bg_scr",
                    "name": "puNG_4",
                    "base": "bg_scr",
                    "str": "99.00",
                    "width": "18.29652996845426%",
                    "height": "23.770491803278688%",
                    "font": "./res/font/bls.ttf",
                    "fontSize": "22px",
                    "fontWeight": 400,
                    "letterSpacing": "0px",
                    "textAlign": "left",
                    "longMode": 0,
                    "baseLine": 6,
                    "color": "rgba(0, 0, 0, 1)",
                    "backgroundColor": "rgba(255, 255, 255, 0)",
                    "display": "block",
                    "objAlign": 1,
                    "xOffset": 458,
                    "yOffset": 400,
                    "top": "76.22950819672131%",
                    "left": "73.18611987381703%"
                },
                "isLock": false,
                "isPriceStatus": true,
                "collapseName": "base",
                "component": "VText",
                "label": "商品名称",
                "type": "label",
                "propValue": "",
                "icon": "wenben",
                "tag": "normal",
                "style": {
                    "rotate": 0,
                    "opacity": 1,
                    "parent": "bg_scr",
                    "name": "puNG_4",
                    "base": "bg_scr",
                    "str": "99.00",
                    "width": 58,
                    "height": 29,
                    "font": "./res/font/bls.ttf",
                    "fontSize": 22,
                    "fontWeight": 400,
                    "lineHeight": "",
                    "letterSpacing": 0,
                    "textAlign": "left",
                    "longMode": 0,
                    "baseLine": 6,
                    "color": "rgba(0, 0, 0, 1)",
                    "backgroundColor": "rgba(255, 255, 255, 0)",
                    "display": false,
                    "objAlign": 1,
                    "xOffset": 458,
                    "yOffset": 400,
                    "top": 400,
                    "left": 458
                },
                "id": "v1nLPR3_50bltNoRIUKsA"
            },
            {
                "groupStyle": {
                    "transform": "rotate(0deg)",
                    "opacity": 1,
                    "name": "gpulG",
                    "parent": "bg_scr",
                    "width": "54.25867507886435%",
                    "height": "0.819672131147541%",
                    "backgroundColor": "rgba(159, 153, 153, 1)",
                    "display": "block",
                    "objAlign": 1,
                    "xOffset": 367,
                    "yOffset": 414,
                    "top": "87.70491803278688%",
                    "left": "44.479495268138805%",
                    "base": "bg_scr"
                },
                "isLock": false,
                "isPriceStatus": true,
                "collapseName": "base",
                "component": "LineShape",
                "label": "线条",
                "propValue": "",
                "type": "line",
                "icon": "zhixian",
                "tag": "normal",
                "style": {
                    "rotate": 0,
                    "opacity": 1,
                    "name": "gpulG",
                    "parent": "bg_scr",
                    "width": 172,
                    "height": 1,
                    "backgroundColor": "rgba(159, 153, 153, 1)",
                    "display": false,
                    "objAlign": 1,
                    "xOffset": 367,
                    "yOffset": 414,
                    "top": 414,
                    "left": 367,
                    "base": "bg_scr"
                },
                "id": "dJJr4zvqunLfLIndxZ1xn"
            }
        ],
        "type": "group"
    }
]

export default priceStatusList